# Generated by Django 5.0.2 on 2025-05-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Quyền', 'verbose_name_plural': 'Quyền'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Vai trò', 'verbose_name_plural': 'Vai trò'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Thông tin người dùng', 'verbose_name_plural': 'Thông tin người dùng'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hoạt động cuối'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP đăng nhập cuối'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role_type',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('manager', 'Manager'), ('tenant', 'Tenant')], default='tenant', max_length=20, verbose_name='Loại vai trò'),
        ),
    ]
