# Generated by Django 5.0.2 on 2025-05-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_permission_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Khóa'), ('pending', 'Chờ Admin xác nhận')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
