# Generated by Django 5.0.3 on 2025-05-07 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã thiết bị')),
                ('name', models.CharField(max_length=255, verbose_name='Tên thiết bị')),
                ('device_type', models.CharField(max_length=100, verbose_name='Loại thiết bị')),
                ('group', models.CharField(choices=[('office', 'Thiết bị văn phòng'), ('classroom', 'Thiết bị phòng học'), ('common', 'Thiết bị chung')], max_length=20, verbose_name='Nhóm thiết bị')),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('broken', 'Hỏng'), ('maintenance', 'Đang bảo trì')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.room', verbose_name='Vị trí (Phòng)')),
            ],
        ),
    ]
