from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard_view, name='dashboard'),
    path('devices/', views.tenant_devices_view, name='tenant_devices'),
    path('devices/add/', views.tenant_add_device_view, name='tenant_add_device'),
    path('devices/delete/', views.tenant_delete_device, name='tenant_delete_device'),
    path('devices/edit/', views.tenant_edit_device, name='tenant_edit_device'),
    path('devices/request-maintenance/', views.tenant_request_maintenance, name='tenant_request_maintenance'),
    path('requests/', views.tenant_requests_view, name='tenant_requests'),
    path('history/', views.tenant_history_view, name='tenant_history'),
    path('account/', views.tenant_account_view, name='tenant_account'),
    path('account/change-password/', views.TenantPasswordChangeView.as_view(), name='tenant_change_password'),
    path('account/update-info/', views.tenant_update_info, name='tenant_update_info'),
    path('add-device-request/', views.tenant_add_device_request, name='tenant_add_device_request'),
    path('contact-manager/', views.tenant_contact_manager, name='tenant_contact_manager'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('account/settings/', views.account_settings_view, name='account_settings'),
    path('devices/<int:device_id>/detail/', views.tenant_device_detail_view, name='tenant_device_detail'),
    path('devices/<int:device_id>/edit/', views.tenant_device_edit_view, name='tenant_device_edit'),
    path('requests/<int:request_id>/detail/', views.tenant_request_detail_view, name='tenant_request_detail'),
    path('rate_task/', views.rate_task_view, name='rate_task'),
    path('manager/devices/', views.manager_devices_view, name='manager_devices'),
    path('manager/devices/<int:device_id>/detail/', views.manager_device_detail_view, name='manager_device_detail'),
    path('manager/devices/<int:device_id>/edit/', views.manager_device_edit_view, name='manager_device_edit'),
    path('manager/devices/delete/', views.manager_delete_device, name='manager_delete_device'),
    path('manager/requests/', views.manager_requests_view, name='manager_requests'),
    path('manager/reports/', views.manager_reports_view, name='manager_reports'),
    path('manager/account/', views.manager_account_view, name='manager_account'),
    path('manager/requests/<int:request_id>/detail/', views.manager_request_detail_view, name='manager_request_detail'),
    path('manager/account/change-password/', views.ManagerPasswordChangeView.as_view(), name='manager_change_password'),
    path('manager/account/update-info/', views.manager_update_info, name='manager_update_info'),
    path('manager/api/chart-data/', views.manager_chart_data_api, name='manager_chart_data_api'),
    path('manager/api/save-chart/', views.manager_save_chart, name='manager_save_chart'),
    path('manager/api/list-charts/', views.manager_list_charts, name='manager_list_charts'),
    path('manager/device-requests/', views.manager_device_requests_view, name='manager_device_requests'),
    path('manager/api/approve-device-request/', views.manager_approve_device_request, name='manager_approve_device_request'),
    path('manager/charts/<int:chart_id>/detail/', views.manager_chart_detail_view, name='manager_chart_detail'),
    path('notifications/<int:notification_id>/', views.notification_detail_view, name='notification_detail'),
    path('maintenance/tasks/', views.maintenance_tasks_view, name='maintenance_tasks'),
    path('maintenance/history/', views.maintenance_history_view, name='maintenance_history'),
    path('maintenance/account/', views.maintenance_account_view, name='maintenance_account'),
    path('maintenance/tasks/<int:task_id>/', views.maintenance_task_detail_view, name='maintenance_task_detail'),
    path('maintenance/tasks/<int:task_id>/start/', views.start_task_view, name='maintenance_task_start'),
    path('maintenance/tasks/<int:task_id>/complete/', views.complete_task_view, name='maintenance_task_complete'),
    path('maintenance/tasks/<int:task_id>/update_progress/', views.update_task_progress, name='maintenance_update_task_progress'),
    path('manager/reports/delete_chart/<int:chart_id>/', views.manager_delete_chart, name='manager_delete_chart'),
] 