# Generated by Django 5.0.2 on 2025-05-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_maintenancerequest_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày đánh giá'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Đánh giá (số sao)'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='rating_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Bình luận đánh giá'),
        ),
    ]
