# Generated by Django 5.0.2 on 2025-05-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_merge_20250526_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('ac', 'Air Conditioner'), ('light', 'Lighting'), ('security', 'Security System'), ('other', 'Other')], max_length=50),
        ),
    ]
