# Generated by Django 5.0.2 on 2025-05-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_device_created_at_alter_device_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='type',
            new_name='device_type',
        ),
    ]
