# Generated by Django 5.0.2 on 2025-05-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_maintenancetask_rated_at_maintenancetask_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tiến độ (%)'),
        ),
    ]
