# Generated by Django 5.0.2 on 2025-05-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_add_device_fields'),
        ('dashboard', '0006_maintenancetask_progress'),
    ]

    operations = [
    ]
