# Generated by Django 5.0.3 on 2025-05-10 12:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True, verbose_name='ID Thiết bị')),
                ('name', models.CharField(max_length=200, verbose_name='Tên Thiết bị')),
                ('device_type', models.CharField(choices=[('server', 'Máy chủ'), ('network', 'Thiết bị mạng'), ('storage', 'Lưu trữ'), ('pc', 'Máy tính cá nhân'), ('monitor', 'Màn hình'), ('other', 'Khác')], max_length=50, verbose_name='Loại')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('maintenance', 'Đang bảo trì'), ('inactive', 'Không hoạt động'), ('broken', 'Hỏng'), ('in_storage', 'Lưu kho')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vị trí')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Ngày mua')),
                ('warranty_expiry_date', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn bảo hành')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Ngày bảo trì cuối')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Ngày bảo trì kế tiếp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thiết bị',
                'verbose_name_plural': 'Thiết bị',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='bmsync_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='bmsync_user_permissions_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50, unique=True, verbose_name='ID Yêu cầu')),
                ('request_type', models.CharField(choices=[('maintenance', 'Bảo trì'), ('repair', 'Sửa chữa'), ('loan', 'Mượn thiết bị')], default='maintenance', max_length=20, verbose_name='Loại yêu cầu')),
                ('description', models.TextField(verbose_name='Mô tả sự cố/Yêu cầu')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('assigned', 'Đã giao'), ('in_progress', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày báo cáo')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('priority', models.IntegerField(default=3, help_text='1=Cao, 2=Trung bình, 3=Thấp', verbose_name='Độ ưu tiên')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bmsync.device', verbose_name='Thiết bị')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='bmsync.user', verbose_name='Người xử lý')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_requests', to='bmsync.user', verbose_name='Người báo cáo')),
            ],
            options={
                'verbose_name': 'Yêu cầu Bảo trì/Mượn',
                'verbose_name_plural': 'Các Yêu cầu Bảo trì/Mượn',
                'ordering': ['-report_date'],
            },
        ),
    ]
