# Generated by Django 5.0.3 on 2025-05-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phòng ban'),
        ),
    ]
