# Generated by Django 5.0.3 on 2025-05-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsync', '0002_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Hoạt động'), ('locked', 'Khóa'), ('pending', 'Chờ Xác nhận')], default='pending', max_length=20, verbose_name='Trạng thái tài khoản'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('desktop_pc', 'Máy tính để bàn'), ('laptop', 'Máy tính xách tay'), ('monitor', 'Màn hình máy tính'), ('printer', 'Máy in'), ('photocopier', 'Máy photocopy'), ('projector', 'Máy chiếu'), ('desk_phone', 'Điện thoại bàn'), ('network_device', 'Thiết bị mạng (Router/Switch)'), ('scanner', 'Máy scan'), ('ups', 'Bộ lưu điện (UPS)'), ('server', 'Máy chủ'), ('storage', 'Thiết bị lưu trữ'), ('other', 'Khác')], max_length=50, verbose_name='Loại'),
        ),
    ]
