# Generated by Django 5.0.3 on 2025-05-11 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsync', '0003_user_account_status_alter_device_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Nội dung thông báo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('notification_type', models.CharField(choices=[('new_user', 'Người dùng mới cần xác nhận'), ('new_request', 'Yêu cầu mới (mượn/bảo trì)'), ('request_processed', 'Yêu cầu đã xử lý'), ('task_assigned', 'Công việc được giao'), ('task_completed', 'Công việc đã hoàn thành'), ('warranty_reminder', 'Nhắc nhở hết hạn bảo hành thiết bị'), ('maintenance_reminder', 'Nhắc nhở lịch bảo trì thiết bị'), ('other', 'Khác')], max_length=50, verbose_name='Loại thông báo')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID đối tượng liên quan')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bmsync.user', verbose_name='Người nhận')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-timestamp'],
            },
        ),
    ]
