# Generated by Django 5.0.3 on 2025-05-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsync', '0004_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-report_date'], 'verbose_name': 'Yêu cầu Công việc', 'verbose_name_plural': 'Các Yêu cầu Công việc'},
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='request_type',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='job_type',
            field=models.CharField(choices=[('loan', 'Mượn'), ('maintenance', 'Bảo trì')], default='maintenance', max_length=20, verbose_name='Công việc'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='description',
            field=models.TextField(verbose_name='Mô tả'),
        ),
    ]
