# Generated by Django 5.0.3 on 2025-05-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsync', '0005_alter_maintenancerequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='notification_status',
            field=models.CharField(choices=[('not_sent', 'Chưa gửi'), ('sent', 'Đã gửi')], default='not_sent', max_length=10, verbose_name='Trạng thái thông báo'),
        ),
    ]
