# Generated by Django 5.0.3 on 2025-05-13 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsync', '0006_maintenancerequest_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests_v2', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_requests_v2', to=settings.AUTH_USER_MODEL, verbose_name='Người báo cáo'),
        ),
    ]
